In [2]:
import pandas as pd

In [17]:
pd.set_option("max_colwidth", None)

In [18]:
df = pd.read_csv('csv_example_output.csv')
df[['Cluster ID','confidence_score','Site name','Address','Zip','Phone']].head(10)

,Cluster ID,confidence_score,Site name,Address,Zip,Phone
0,0,0.963386,Salvation Army - Temple / Salvation Army,1 N Ogden Ave,NaN,2262649.0
1,0,0.963386,Salvation Army - Temple / Salvation Army,1 N Ogden Ave,NaN,2262649.0
2,9,0.755361,National Louis University - Dr. Effie O. Ellis Training Center,10 S Kedzie Ave,NaN,5339011.0
3,9,0.755361,National Louis University - Dr. Effie O. Ellis Training Center,10 S Kedzie Ave,NaN,5339011.0
4,10,0.766560,Board Trustees-City Colleges of Chicago - Olive-Harvey College,10001 S Woodlawn Ave,NaN,2916100.0
5,10,0.766560,Board Trustees-City Colleges of Chicago - Olive-Harvey College,10001 S Woodlawn Ave,NaN,2916100.0
6,11,0.889324,Easter Seals Society of Metropolitan Chicago - Gilchrist-Marchman,1001 W Roosevelt Rd,NaN,9395115.0
7,11,0.889324,Easter Seals Society of Metropolitan Chicago - Gilchrist-Marchman,1001 W Roosevelt Rd,NaN,9395115.0
8,15,0.995987,Hull House Association - Uptown Head Start / Hull House,1020 W Bryn Mawr Ave,NaN,7695753.0
9,17,0.998559,Hull House Association - Child Dev. Central Office- Hull House CDS-Homes,1030 W Van Buren St,NaN,9068600.0

In [20]:
original = pd.read_csv('csv_example_messy_input.csv')
original[['Site name','Address','Zip','Phone']].head(10)

,Site name,Address,Zip,Phone
0,Salvation Army - Temple / Salvation Army,1 N Ogden Ave,NaN,2262649.0
1,Salvation Army - Temple / Salvation Army,1 N Ogden Ave,NaN,2262649.0
2,National Louis University - Dr. Effie O. Ellis Training Center,10 S Kedzie Ave,NaN,5339011.0
3,National Louis University - Dr. Effie O. Ellis Training Center,10 S Kedzie Ave,NaN,5339011.0
4,Board Trustees-City Colleges of Chicago - Olive-Harvey College,10001 S Woodlawn Ave,NaN,2916100.0
5,Board Trustees-City Colleges of Chicago - Olive-Harvey College,10001 S Woodlawn Ave,NaN,2916100.0
6,Easter Seals Society of Metropolitan Chicago - Gilchrist-Marchman,1001 W Roosevelt Rd,NaN,9395115.0
7,Easter Seals Society of Metropolitan Chicago - Gilchrist-Marchman,1001 W Roosevelt Rd,NaN,9395115.0
8,Hull House Association - Uptown Head Start / Hull House,1020 W Bryn Mawr Ave,NaN,7695753.0
9,Hull House Association - Child Dev. Central Office- Hull House CDS-Homes,1030 W Van Buren St,NaN,9068600.0